on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install    
        env:
          CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: react-github-actions-build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Deploy to S3
        run: aws s3 sync build/ s3://react-github-actions --acl public-read

  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: react-github-actions-build
      - name: Zip build
        uses: actions/zip@v2
        with:
          files: react-github-actions-build/**
          path: react-github-actions-release-build.zip
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: react-github-actions-release-build.zip
          body: https://react-github-actions.s3.amazonaws.com/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
